services:
  # --- Service Base de Données (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: devops-db
    restart: always
    # Charge les variables depuis backend/.env (POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB)
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"  # Accès local possible sur localhost:5432
    volumes:
      - db_data:/var/lib/postgresql/data  # Persistance des données (volume géré par Docker)

  # --- Service Backend (API) ---
  backend:
    build: ./backend  # Construit l'image à partir du dossier backend
    container_name: devops-backend
    restart: always
    ports:
      - "5000:5000"
    # Injecte toutes les variables de backend/.env dans le conteneur backend
    env_file:
      - ./backend/.env
    # Monte également le fichier .env dans le conteneur pour les charges explicites
    volumes:
      - ./backend/.env:/app/.env:ro
    depends_on:
      - db  # Attend que la DB soit lancée avant de démarrer

  # --- Service Frontend (React/Nginx) ---
  frontend:
    build: ./frontend # Construit l'image à partir du dossier frontend
    container_name: devops-frontend
    restart: always
    ports:
      - "8080:80"     # On mappe le port 80 du conteneur (Nginx) sur le port 8080 de ta machine
    depends_on:
      - backend       # Bonnes pratiques, même si techniquement indépendant au démarrage

volumes:
  db_data:            # Déclaration du volume pour la persistance
