apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: postgres
  DB_PORT: "5432"
  FRONTEND_URL: "http://4.178.2.160"
  DB_USER: "postgres"
  DB_NAME: "vote2earn"
  JWT_EXPIRES_IN: "1d"
